### ISSUE TITLE
profile edit 화면

### ISSUE THREAD

**Issue by summermermer** [SKKU-OSP/SKKU-OSP#16]
@meltingOcean 

- [x] 태그 추가 시 전체 새로고침됨
- [x] 프로필 저장 눌렀을때 본인 프로필로 자동 넘어가기
- [x] 자기소개에서 한줄소개가 표시되고/ 아래는 detail이라고 guide글씨로 써놓으면 좋을듯
- [x] 프로그래스바에 초급/숙련/장인 guidline
- [x] 프로그래스바 눈금 있으면 좋을듯
- [x] 관심분야 x표 안보임
- [x] 다른 계정 프로필 화면에는 수정 버튼 가리기
- [x] 프로필 이미지 바꾸기 버튼 
- [x] 프로필이 성공적으로 저장됐습니다 메세지 상단에 띄우기
- [x] 이 현상 해결 
![image](https://user-images.githubusercontent.com/68227738/183604983-bd819fca-399f-4c5d-86d7-4fd091e03335.png)

**Comment by meltingOcean** [comment]
확인완료
작업중

**Comment by meltingOcean** [comment]
1번은 기술적인 문제로 바로 해결하기 힘들것 같습니다.ㅠㅠ

**Comment by summermermer** [comment]
네에 ㅠㅠ

**Comment by summermermer** [comment]
- [ ] github id는 수정이 안되나요?
![image](https://user-images.githubusercontent.com/68227738/183605226-0bb9b234-85ac-4ad4-bbad-e6c2a25a1320.png)

**Comment by meltingOcean** [comment]
깃헙 아이디는 수정이 안됩니다...!

**Comment by summermermer** [comment]
> 깃헙 아이디는 수정이 안됩니다...!

그럼 label로 들어가야 할거같아요 txt box말고..!

**Comment by meltingOcean** [comment]
반영하겠습니다>!
