### ISSUE TITLE
커뮤니티 수정사항

### ISSUE THREAD

**Issue by tsfo1489** [SKKU-OSP/SKKU-OSP#23]
- [x] 게시물 채우기
- [x] Active Article 적용
- [x] User 게시판 추천 알고리즘 적용
- [x] 페이지네이션 디자인 적용
- [x] 게시물 View 디자인 적용
- [x] Modal 디자인 적용
- [ ] #31
- [x] 보낸지원서 템플릿 태그 개발
- [x] 지원서 수정 및 취소 API
- [x] 팀 정보 수정에서 팀 설명 text area로

**Comment by theran23** [comment]
접근권한: 팀멤버가 없으면 이용할 수 없도록
