### ISSUE TITLE
디자인 수정

### ISSUE THREAD

**Issue by summermermer** [SKKU-OSP/SKKU-OSP#29]
- [x] 휴지통 버튼 을 지원 취소 버튼으로 ![image](https://user-images.githubusercontent.com/68227738/184760176-c59b6d9c-971f-4c80-a98a-21f60970a84b.png)

- [x] 얘만 폰트가 커요! ![image](https://user-images.githubusercontent.com/68227738/184770807-9cd1c3ca-0db0-413e-aa7e-e90651d0c012.png)
- [x] ![image](https://user-images.githubusercontent.com/68227738/184780119-9672f5e5-faec-42d7-8040-80f3d382e520.png) 여기 마진 좀 넣어주세요 !
- [x] ![image](https://user-images.githubusercontent.com/68227738/184802867-ed48dad2-2326-490a-b49c-d21eff307421.png) 버튼들 호버 이벤트 주세요 !
- [x] ![image](https://user-images.githubusercontent.com/68227738/184810388-a6560e6e-7ca8-438b-bf83-f98bbb070a29.png) 수정 사항이 두가지: 1) 드롭 접었을 때 색 적용 안돼있습니다 2) 개인/전체 섹션 css 변경 
- [x] ![image](https://user-images.githubusercontent.com/68227738/184937347-d3afa40a-4e4d-42b4-b878-abb841513016.png) 모집중/ 마감 이랑 태그랑 잘 구별이 안된다 제목 옆이나 앞쪽에 모집을 띄우는 게 나을듯

**Comment by SeoJeongYeop** [comment]
모두 개선 완료했습니다. 감사합니다.
