### ISSUE TITLE
개발자 성향

### ISSUE THREAD

**Issue by summermermer** [SKKU-OSP/SKKU-OSP#30]
- [x] 한글 description 추가
- [x] 결과 없을때는 모달 창 열었을때 검사하기 버튼 ->지금은 검사 진행할 방법이 없어요
- [x] 이미지 저장할 때 ![image](https://user-images.githubusercontent.com/68227738/184773928-f1697737-1fc1-4e4a-9d2a-771cc5da4192.png) 이렇게 배경까지 캡쳐 가능할까요?
- [x] ![image](https://user-images.githubusercontent.com/68227738/184774580-0f6c10cb-e993-4ccb-84c6-554ff9507306.png) 이미지 크기 좀만 줄이기

**Comment by SeoJeongYeop** [comment]
추가 개발자 성향 개선 내용
- [ ] 개발자 유형 검사 프로그레스바 radius
- [ ] 개발자 유형 검사 desc 폰트 사이즈 축소
- [ ] 개발자 성향 분석 그래프 radius

**Comment by SeoJeongYeop** [comment]
개발자 성향 디자인 개선 완료했습니다
