### ISSUE TITLE
사소한 수정 사항

### ISSUE THREAD

**Issue by summermermer** [SKKU-OSP/SKKU-OSP#32]
- [x] ![image](https://user-images.githubusercontent.com/68227738/187160433-71c98434-8218-44d9-99fc-36ab29eb1c37.png) 게시판 버그
- [x] ![image](https://user-images.githubusercontent.com/68227738/187160625-5744f60c-5c11-46fb-8c54-c393fedb1f7b.png) 최신 것 위로 올라오게 정렬
- [x] 위 사진. 드롭다운 안되게 고정
- [x] ![image](https://user-images.githubusercontent.com/68227738/187161293-479d803a-2f14-4ed8-be72-eb7cdbe6b68d.png) ![image](https://user-images.githubusercontent.com/68227738/187161336-6dfce58e-81d7-4a9f-8066-1023db7388d6.png) 사진 크기 다름

**Comment by SeoJeongYeop** [comment]
- 게시판의 수정/삭제 버튼 위치 이동했습니다.
- 내 활동 목록을 최신순 정렬하도록 했습니다.
- 내 활동 목록을 탭 형식으로 바꾸면서 드롭다운도 비활성화 했습니다.
- 사진 크기를 같도록 하고 프로필 페이지와 커뮤니티의 사이드바 구조를 비슷하게 바꾸었습니다.
