### ISSUE TITLE
각 페이지 별 잔여 태스크 및 에러

### ISSUE THREAD

**Issue by SeoJeongYeop** [SKKU-OSP/SKKU-OSP#33]
## 프로필

- [x] 세부점수 시각화 5점 초과 점수에 대해 제한 두기
- [x] 파이차트 퍼센티지 표시를 호버할 때가 아닌 차트 영역에 바로 표시
- [x] 개발자 성향 분석의 막대그래프에 y축 레이블 추가

## 프로필 Edit

- [x] 저장할 때 순서가 꼬여서 발생하는 오류 수정
- [x] 버튼을 두 번 눌렀을 때 오브젝트 에러가 표시되는 부분을 예외 처리를 통해 수정
- [x] 사진 바꾸는 것이 늦게 반영되는 오류 수정
- [x] 자기소개에 아무 내용이 없는 상태에서 마크다운을 입력할 수 있음을 알 수 있도록 표시
- [x] 사용 언어 추가했을 때 버블이 사라지는 오류 수정
- [x] 수정 페이지에서 전공 0과 1로 표시하는 부분을 드롭다운 또는 라디오 버튼으로 교체
- [x] secondary email 부분의 column이 넘쳐서 안 보이므로 폰트를 줄이는 등의 조치를 통해 수정
- [x] 사진 바꿀 때 디폴트 이미지가 지워지는 문제 수정
- [x] 추가버튼 더블클릭하면 언어가 두 번 추가되는 현상 수정
- [x] 저장하고 난 뒤에 이미지를 변경했을때 미리보기가 변경이 안되는 현상 수정
- [ ] 사용언어 기술스택 변경한 뒤에 저장하기 하면 레인지 바가 이상하게 바뀌는 현상
## 커뮤니티

- [x] 팀 추천에 따라 팀원 초대 시 다시 팀을 선택하는 것이 불편 → 디폴트로 추천 대상인 팀을 선택하도록 수정
- [ ] 메시지 실시간 기능
- [ ] Ajax를 통해 페이지의 일부분만 띄우는 경우 Ajax 작업 완료 시까지 로딩바를 표시하도록 수정
- [x] 지원서 승인/거절 받음-> 알림 클릭 시 지원서 목록으로 링크되는데, 지원서가 삭제돼서 아무것도 없음. 지원서를 남겨두고 승인/ 거절 상태를 표기하거나 링크를 팀 게시판으로 하거나 
- [x] ![image](https://user-images.githubusercontent.com/68227738/190161919-06ab633d-5125-4e49-839d-6911b7ae7f81.png) 사용자 선택 안되는데 보내짐 + 메세지 없는데 보내짐
- [x] ![image](https://user-images.githubusercontent.com/68227738/190164399-d6407a48-bd22-4c28-8d03-cc25e7c1ab40.png)  

## 리포지토리

- [x] student contributor: hover 할 때마다 Ajax 실행하는 구현방식 수정

**Comment by meltingOcean** [comment]
수정중입니다.

**Comment by meltingOcean** [comment]
구 버전 이슈로 close 합니다.
